service: server

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 100

functions:
  generate:
    handler: handler.generate
    events:
      - http:
          path: generate
          method: post
          cors: true

plugins:
  - serverless-offline